import {StyleSheet} from 'react-native';

const style = StyleSheet.create({
  background: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: 'rgba(0,0,0,0.8)',
  },

  Cima: {
    width: '100%',
    height: '40%',
    alignItems: 'center',
    justifyContent: 'center',
    // borderBottomWidth: 3,
    // borderBottomColor: '#478F0F',
  },

  container: {
    width: '90%',
    height: '70%',
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderTopRightRadius: 50,
    borderTopLeftRadius: 5,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.3)',
    borderBottomWidth: 5,
    borderBottomColor: '#478F0F',
    padding: 5,
  },

  boxImage: {
    height: '100%',
    width: '40%',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  candidato: {
    width: 100,
    height: 100,
    borderWidth: 2,
    borderColor: '#fff',
    borderRadius: 50,
  },
  numeroCandidato: {
    fontSize: 20,
    fontWeight: '900',
    color: '#fff',
  },
  boxTexto: {
    width: 200,
    flex: 1,
  },
  texto: {
    fontSize: 14,
    fontWeight: '500',
    color: '#fff',
    fontStyle: 'italic',
    height: 40,
  },
  meio: {
    width: '100%',
    height: '20%',
    alignItems: 'center',
    justifyContent: 'space-around',
    borderBottomWidth: 3,
    borderBottomColor: '#478F0F',
    marginBottom: 10,
  },
  botaoVotar: {
    alignItems: 'center',
    width: '40%',
    height: 45,
    backgroundColor: 'rgba(0,255,0,0.4)',
    borderBottomWidth: 4,
    borderBottomColor: '#111',
    borderRightWidth: 4,
    borderRightColor: '#111',
    borderRadius: 10,
    shadowColor: 'rgba(0,0,0,0.9)',
    shadowRadius: 20,
    shadowOpacity: 0.1,
    elevation: 8,
    shadowOffset: {
      width: 10,
      height: 10,
    },
  },
  botaoInfo: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '30%',
    height: 30,
    backgroundColor: 'rgba(255,255,255,0.5)',
    borderBottomWidth: 4,
    borderBottomColor: '#111',
    borderRightWidth: 4,
    borderRightColor: '#111',
    borderBottomLeftRadius: 15,
    borderTopRightRadius: 15,
    shadowColor: 'rgba(0,0,0,0.9)',
    shadowRadius: 20,
    shadowOpacity: 0.1,
    elevation: 8,
    shadowOffset: {
      width: 10,
      height: 10,
    },
  },
  baixo: {
    width: '100%',
    height: '40%',
  },
  HFlat: {
    marginVertical: 5,
  },
  boxText: {
    width: '80%',
    height: '70%',
    paddingLeft: 20,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  textoDados: {
    fontSize: 18,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.5)',
    textAlign:'center',
    fontFamily: 'serif',
  },
  boxDados: {
    marginTop: 10,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0)',
  },
  textoDados2: {
    marginHorizontal: 5,
    fontSize: 18,
    fontWeight: '900',
    color: '#fff',
    fontStyle:'italic',
    fontFamily:'san-serif',
  },
  

  //Modal (
  backgroundModal: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  botaoVoltar: {
    width: 50,
    height: '8%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    alignSelf: 'flex-end',
  },
  //--------------
  containerView: {
    width: '100%',
    height: '45%',
  },
  boxTextoVoto: {
    width: '60%',
    height: '100%',
    marginLeft: 25,
  },
  textoVoto: {
    color: 'white',
    fontSize: 25,
    fontWeight: '900',
  },
  logo: {
    width: '40%',
    height: '100%',
  },
  //------------------
  containerModal: {
    width: '90%',
    height: '55%',
    backgroundColor: '#F3F3F3',
    alignSelf: 'center',
    flexDirection: 'row',
    borderRadius: 10,
  },
  imageModal: {
    height: '100%',
    width: '40%',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  textoCandidato: {
    color: 'black',
    fontSize: 18,
    fontWeight: '900',
  },
  dadosModal: {
    width: '60%',
    height: '100%',
    justifyContent: 'space-between',
    paddingVertical: 25,
  },
  textoDadosModal: {
    color: 'black',
    fontSize: 14,
    fontWeight: '500',
  },
  //-----------------

  teclado: {
    width: '90%',
    height: '46%',
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  numeroTeclado: {
    width: '100%',
    height: '78%',
    flexWrap: 'wrap',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  botaoN: {
    width: 80,
    height: 40,
    borderRadius: 5,
    backgroundColor: '#111',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
    marginVertical: 7,
    shadowColor: 'black',
    shadowRadius: 10,
    shadowOpacity: 0.1,
    elevation: 8,
    shadowOffset: {
      width: 10,
      height: 10,
    },
  },
  textoTeclado: {
    width: '100%',
    height: '22%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  botaoBranco: {
    padding: 15,
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'black',
    shadowRadius: 10,
    shadowOpacity: 0.1,
    elevation: 8,
    shadowOffset: {
      width: 10,
      height: 10,
    },
  },
  botaoCorrige: {
    padding: 15,
    borderRadius: 5,
    marginHorizontal: 10,
    backgroundColor: '#F82525',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'black',
    shadowRadius: 10,
    shadowOpacity: 0.1,
    elevation: 8,
    shadowOffset: {
      width: 10,
      height: 10,
    },
  },
  botaoConfirma: {
    padding: 15,
    borderRadius: 5,
    backgroundColor: '#0FEF3C',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'black',
    shadowRadius: 10,
    shadowOpacity: 0.1,
    elevation: 8,
    shadowOffset: {
      width: 10,
      height: 10,
    },
  },

  // )
});

export default style;
